name: Jo
favicon: null
layout_spectrum: 0.6590043
typography_spectrum: 0.8607867
title: Jo on the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9662684
  lightness: 0.4721646
  saturation: 0.1320259
  rhythmicContrast: 0.704695
purpose: []
