typography_spectrum: 0.8607867
color:
  brandColors: []
  brandStrength: 0.9662684
  lightness: 0.4721646
  saturation: 0.1320259
  rhythmicContrast: 0.704695
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03468
analytics:
  google: null
  facebook: null
  twitter: null
name: ellenberg.digital
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: radically different
purpose: []
